package com.min.smalltalk.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.min.smalltalk.bean.FriendInfo;
import com.min.smalltalk.bean.GroupMember;
import com.min.smalltalk.bean.Groups;

import com.min.smalltalk.db.FriendInfoDao;
import com.min.smalltalk.db.GroupMemberDao;
import com.min.smalltalk.db.GroupsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendInfoDaoConfig;
    private final DaoConfig groupMemberDaoConfig;
    private final DaoConfig groupsDaoConfig;

    private final FriendInfoDao friendInfoDao;
    private final GroupMemberDao groupMemberDao;
    private final GroupsDao groupsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendInfoDaoConfig = daoConfigMap.get(FriendInfoDao.class).clone();
        friendInfoDaoConfig.initIdentityScope(type);

        groupMemberDaoConfig = daoConfigMap.get(GroupMemberDao.class).clone();
        groupMemberDaoConfig.initIdentityScope(type);

        groupsDaoConfig = daoConfigMap.get(GroupsDao.class).clone();
        groupsDaoConfig.initIdentityScope(type);

        friendInfoDao = new FriendInfoDao(friendInfoDaoConfig, this);
        groupMemberDao = new GroupMemberDao(groupMemberDaoConfig, this);
        groupsDao = new GroupsDao(groupsDaoConfig, this);

        registerDao(FriendInfo.class, friendInfoDao);
        registerDao(GroupMember.class, groupMemberDao);
        registerDao(Groups.class, groupsDao);
    }
    
    public void clear() {
        friendInfoDaoConfig.clearIdentityScope();
        groupMemberDaoConfig.clearIdentityScope();
        groupsDaoConfig.clearIdentityScope();
    }

    public FriendInfoDao getFriendInfoDao() {
        return friendInfoDao;
    }

    public GroupMemberDao getGroupMemberDao() {
        return groupMemberDao;
    }

    public GroupsDao getGroupsDao() {
        return groupsDao;
    }

}
