package com.min.smalltalk.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.min.smalltalk.bean.FriendInfo;

import com.min.smalltalk.db.FriendInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendInfoDaoConfig;

    private final FriendInfoDao friendInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendInfoDaoConfig = daoConfigMap.get(FriendInfoDao.class).clone();
        friendInfoDaoConfig.initIdentityScope(type);

        friendInfoDao = new FriendInfoDao(friendInfoDaoConfig, this);

        registerDao(FriendInfo.class, friendInfoDao);
    }
    
    public void clear() {
        friendInfoDaoConfig.clearIdentityScope();
    }

    public FriendInfoDao getFriendInfoDao() {
        return friendInfoDao;
    }

}
